RootNode:
    BaseYaml: ../../../CommonForms/PetraEditForm.yaml
    FormTitle: Maintain Application Types
    Namespace: Ict.Petra.Client.MPersonnel.Gui.Setup
    DetailTable: PtApplicationType
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data,Ict.Petra.Shared.MPersonnel.Personnel.Validation,Ict.Petra.Shared.Interfaces.MCommon]
    FormType: edit
    Template: windowMaintainTable
    WindowWidth: 750
    WindowHeight: 400
    Actions:
        actNew: {Label=&New, ActionClick=NewRecord}
        actDelete: {Label=&Delete, ActionClick=DeleteRecord}
    Controls:
        pnlContent:
            Controls: [pnlGrid, pnlDetails]
            Dock: Fill
        pnlGrid:
            Dock: Fill
            Controls: [pnlFilterAndFind, pnlButtons, grdDetails]
        pnlFilterAndFind:
            ExpandedWidth: 175
            FilterControls: [txtDetailAppTypeName, txtDetailAppTypeDescr, rgrDetailAppFormType, chkDetailDeletableFlag]
            FindControls: [txtDetailAppTypeName, txtDetailAppTypeDescr]
            ControlAttributes:
                rgrDetailAppFormType: {CloneToComboBox=true, Label=Application For}
        pnlButtons:
            Dock: Bottom
            Controls: [btnNew, btnDelete]
            ControlsOrientation: horizontal
        btnNew:
            Action: actNew
            Width: 80
        btnDelete:
            Action: actDelete
            Width: 80
        grdDetails:
            Dock: Fill
            Columns: []
            ActionFocusRow: FocusedRowChanged
        pnlDetails:
            Dock: Bottom
            Controls:
                Row0: [txtDetailAppTypeName, txtDetailAppTypeDescr]
                Row1: [rgrDetailAppFormType]
                Row2: [chkDetailUnassignableFlag, dtpDetailUnassignableDate]
                Row3: [chkDetailDeletableFlag]                
        rgrDetailAppFormType:
            Controls: [rbtEvent, rbtField]
            Label: Application for
            BorderVisible: false
            Margin: 120,0,0,0
            ControlsOrientation: horizontal
        rbtEvent:
            Label: Event
            ParameterValue: SHORT FORM
        rbtField:
            Label: Field
            ParameterValue: LONG FORM
        txtDetailAppTypeName: {Label=Application Type, CharacterCasing=Upper}
        txtDetailAppTypeDescr: {Label=Description, Width=300}
        chkDetailUnassignableFlag: {Label=Unassignable, OnChange=EnableDisableUnassignableDate}
        dtpDetailUnassignableDate: {Label=Unassignable Date, Enabled=false, Validation=true}
        chkDetailDeletableFlag: {Label=Deletable}
