RootNode:
    BaseYaml: ../../../CommonForms/PetraEditForm.yaml
    FormTitle: Maintain Application Types
    Namespace: Ict.Petra.Client.MPersonnel.Gui.Setup
    DetailTable: PtApplicationType
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data,Ict.Petra.Shared.MPersonnel.Personnel.Validation,Ict.Petra.Shared.Interfaces.MCommon]
    FormType: edit
    Template: windowMaintainTable
    WindowWidth: 750
    WindowHeight: 400
    Actions:
        actNew: {Label=New, ActionClick=NewRecord}
    Controls:
        pnlContent:
            Controls: [pnlGrid, pnlDetails]
            Dock: Fill
        pnlGrid:
            Dock: Fill
            Controls: [grdDetails, pnlButtons]
        pnlButtons:
            Dock: Right
            Controls: [btnNew]
        btnNew:
        grdDetails:
            Dock: Fill
            Columns: []
            ActionFocusRow: FocusedRowChanged
        pnlDetails:
            Dock: Bottom
            Controls:
                Row0: [txtDetailAppTypeName, txtDetailAppTypeDescr]
                Row1: [rgrDetailAppFormType]
                Row2: [chkDetailUnassignableFlag, dtpDetailUnassignableDate]
                Row3: [chkDetailDeletableFlag]                
        rgrDetailAppFormType:
            Controls: [rbtEvent, rbtField]
            Label: Application for
            BorderVisible: false
            ControlsOrientation: horizontal
        rbtEvent:
            Label: Event
            ParameterValue: SHORT FORM
        rbtField:
            Label: Field
            ParameterValue: LONG FORM
        txtDetailAppTypeName: {Label=Application Type, CharacterCasing=Upper}
        txtDetailAppTypeDescr: {Label=Description, Width=110}
        chkDetailUnassignableFlag: {Label=Unassignable, OnChange=EnableDisableUnassignableDate}
        dtpDetailUnassignableDate: {Label=Unassignable Date, Enabled=false, Validation=true}
        chkDetailDeletableFlag: {Label=Deletable}
    Toolbar:
        tbbNew:
            Label: New Application Type
