RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data,Ict.Petra.Shared.MPersonnel.Personnel.Validation]
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrol
    MasterTable: PmGeneralApplication
    Actions:
    Controls:
        pnlDetails:
            Controls: [grpField, grpPlacement]
            AutoScroll: true
            Dock: Fill
        grpField: {NoLabel=true}
            Controls: 
                Row0: [txtField]
                Row1: [dtpAvailableFrom, dtpAvailableTo]
            Dock: Top
        grpPlacement: {NoLabel=true}
            Controls: 
                Row0: [cmbApplicationType]
                Row1: [txtPlacementPerson]
            Dock: Top
              
        txtField: {Label=Field, DataField=PmGeneralApplication.GenAppPossSrvUnitKey, Type=PartnerKey, PartnerClass=UNIT, ColSpan=2, OnChange=ProcessApplicationFieldChanged, Validation=true, Stretch=horizontally}
        dtpAvailableFrom: {Label=Available from, DataField=PmYearProgramApplication.StartOfCommitment, Validation=true}
        dtpAvailableTo: {Label=Available to, DataField=PmYearProgramApplication.EndOfCommitment, Validation=Pair(dtpAvailableFrom)}

        cmbApplicationType: {Label=Application Type, List=FieldApplicationTypeList, DataField=PmGeneralApplication.AppTypeName, Validation=true, Stretch=horizontally}
        txtPlacementPerson: {Label=Placement Person, DataField=PmGeneralApplication.PlacementPartnerKey, Type=PartnerKey, PartnerClass=PERSON, Stretch=horizontally}
        
