RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data,Ict.Petra.Shared.MPersonnel.Personnel.Validation]
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrol
    MasterTable: PmGeneralApplication
    Actions:
    Controls:
        pnlDetails:
            Controls: [grpEventInfo, grpMiscellaneous]
            AutoScroll: true
            Dock: Fill
        grpEventInfo: {NoLabel=true}
            Controls: 
                Row0: [txtEvent]
                Row1: [txtFieldCharged]
            Dock: Top
        grpMiscellaneous: {NoLabel=true}
            Controls: 
                Row0: [cmbApplicationType]
                Row1: [cmbContact1]
                Row2: [cmbContact2]
                Row3: [txtPlacementPerson]
            Dock: Top
              
        txtEvent: {Label=Event, DataField=PmShortTermApplication.StConfirmedOption, Type=Event, OnChange=ProcessApplicationEventChanged, Validation=true, Stretch=horizontally}
        txtFieldCharged: {Label=Field Charged, DataField=PmShortTermApplication.StFieldCharged, Type=PartnerKey, PartnerClass=UNIT, Validation=true, Stretch=horizontally}

        cmbApplicationType: {Label=Application Type, List=EventApplicationTypeList, DataField=PmGeneralApplication.AppTypeName, Validation=true, Stretch=horizontally}
        cmbContact1: {Label=Organization Contact 1, List=ContactList, DataField=PmGeneralApplication.GenContact1, Width=500, AllowDbNull=true}
        cmbContact2: {Label=Organization Contact 2, List=ContactList, DataField=PmGeneralApplication.GenContact2, Width=500, AllowDbNull=true}
        txtPlacementPerson: {Label=Placement Person, DataField=PmGeneralApplication.PlacementPartnerKey, Type=PartnerKey, PartnerClass=PERSON, Stretch=horizontally}
        
