RootNode:
    BaseYaml: ../../../CommonForms/PetraEditForm.yaml
    FormTitle: Maintain Conference Master Settings
    Namespace: Ict.Petra.Client.MConference.Gui.Setup
    DatasetType: Ict.Petra.Shared.MConference.Data.ConferenceSetupTDS
    MasterTable: PcConference
    UsingNamespaces: [Ict.Petra.Shared.MConference.Data,Ict.Petra.Shared.MPartner.Partner.Data,Ict.Petra.Shared.MConference.Validation]
    ModuleForSecurity: MConference
    FormType: edit
    Template: windowEdit
    WindowWidth: 550
    WindowHeight: 600
    Actions:
        actAddVenue:
            ActionClick: AddVenue
            Tooltip: Add a venue to the conference
        actRemoveVenue:
            ActionClick: RemoveVenue
            Tooltip: Remove a venue from the conference
    Controls:
        pnlContent:
            Dock: Fill
            Controls: [pnlConferenceDetails, grpDiscounts, grpGrid]
        pnlConferenceDetails:
            Controls: 
                Row0: [txtConferenceName]
                Row1: [txtCampaignPrefixCode]
                Row2: [dtpStartDate, dtpEndDate]
                Row3: [cmbCurrency]
                Row4: [rgrAttendanceChargeRadio]
                Row5: [chkAddAccommodationCosts]
            ControlsOrientation: vertical
        pnlGrid:
            Height: 100
            Stretch: horizontally
            Controls: [grdVenues, pnlGridButtons]
        pnlGridButtons:
            Dock: Right
            Controls: [btnAdd, btnRemove]
        grpDiscounts:
            Stretch: horizontally
            ColWidths: [0=Fixed:250, 1=Fixed:130, 2=Fixed:130]
            TabOrder: Horizontal
            Controls:
                Row0: [Empty, lblAttendance, lblAccommodation]
                Row1: [lblSpecialRolePreTitle, txtSpecialRolePreAttendance, txtSpecialRolePreAccommodation]
                Row2: [lblVolunteerPreTitle, txtVolunteerPreAttendance, txtVolunteerPreAccommodation]
                Row3: [lblParticipantPreTitle, txtParticipantPreAttendance, txtParticipantPreAccommodation]
                Row4: [lblSpecialRoleTitle, txtSpecialRoleAttendance, txtSpecialRoleAccommodation]
                Row5: [lblVolunteerTitle, txtVolunteerAttendance, txtVolunteerAccommodation]
                Row6: [lblSpecialRoleCampaignTitle, txtSpecialRoleCampaignAttendance, txtSpecialRoleCampaignAccommodation]
        grpGrid:
            Label: Conference Venues
            Stretch: horizontally
            Controls: [pnlGrid]
        
        rgrAttendanceChargeRadio:
            Controls: [rbtNight, rbtDay, rbtCampaign]
            Label: Conference Attendance Charge:
            BorderVisible: false
            ControlsOrientation: horizontal
            ColSpan: 2
        rbtNight:
            Label: Daily (per Night)
            OnChange: AttendanceChargeChanged
            ParameterValue: Night
        rbtDay:
            Label: Daily (per Day)
            OnChange: AttendanceChargeChanged
            ParameterValue: Day
        rbtCampaign:
            Label: Campaign
            OnChange: AttendanceChargeChanged
            ParameterValue: Campaign
        grdVenues:
            AutoFindColumn: 1
            Dock: Fill
            Stretch: fully
        btnAdd:
            Action: actAddVenue
            Stretch: horizontally
        btnRemove:
            Action: actRemoveVenue
            Stretch: horizontally

        lblAttendance:
        lblAccommodation:
        lblSpecialRolePreTitle: {Label=Special Event Role Pre-Conference}
        lblVolunteerPreTitle: {Label=Volunteer Pre-Conference} 
        lblParticipantPreTitle: {Label=Participant Pre-Conference} 
        lblSpecialRoleTitle: {Label=Special Event Role Conference}
        lblVolunteerTitle: {Label=Volunteer Conference}
        lblSpecialRoleCampaignTitle: {Label=Special Event Role Campaign}
        txtConferenceName: {ReadOnly=true, BorderStyle=None, Stretch=horizontally, ColSpan=2}
        txtCampaignPrefixCode: {ReadOnly=true, BorderStyle=None, Stretch=horizontally, ColSpan=2}
        txtSpecialRolePreAttendance: {NoLabel=true, Width=60, Format=PercentInteger}
        txtSpecialRolePreAccommodation: {NoLabel=true, Width=60, Format=PercentInteger, ReadOnly=true}
        txtVolunteerPreAttendance: {NoLabel=true, Width=60, Format=PercentInteger}
        txtVolunteerPreAccommodation: {NoLabel=true, Width=60, Format=PercentInteger, ReadOnly=true}
        txtParticipantPreAttendance: {NoLabel=true, Width=60, Format=PercentInteger}
        txtParticipantPreAccommodation: {NoLabel=true, Width=60, Format=PercentInteger, ReadOnly=true}
        txtSpecialRoleAttendance: {NoLabel=true, Width=60, Format=PercentInteger}
        txtSpecialRoleAccommodation: {NoLabel=true, Width=60, Format=PercentInteger, ReadOnly=true}
        txtVolunteerAttendance: {NoLabel=true, Width=60, Format=PercentInteger}
        txtVolunteerAccommodation: {NoLabel=true, Width=60, Format=PercentInteger, ReadOnly=true}
        txtSpecialRoleCampaignAttendance: {NoLabel=true, Width=60, Format=PercentInteger}
        txtSpecialRoleCampaignAccommodation: {NoLabel=true, Width=60, Format=PercentInteger, ReadOnly=true}
        dtpStartDate: {ReadOnly=true}
        dtpEndDate: {ReadOnly=true}
        cmbCurrency: {List=CurrencyCodeList, ColSpan=2}
        chkAddAccommodationCosts: {Label=Add accommodation costs to get total costs (per Night), OnChange=UpdateDiscounts, CheckBoxAttachedLabel=right, ColSpan=2}