RootNode:
    BaseYaml: ../../../CommonForms/PetraEditForm.yaml
    FormTitle: Ledger Settings
    Namespace: Ict.Petra.Client.MFinance.Gui.Setup
    UsingNamespaces: [Ict.Petra.Shared.MFinance.Account.Data, Ict.Petra.Shared.MFinance.GL.Data, Ict.Petra.Shared.MFinance.Account.Validation]
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    MasterTable: ALedger
    FormType: edit
    Template: windowEdit
    WindowWidth: 700
    WindowHeight: 600
    Controls:
        pnlContent:
            Dock: Fill
            Controls: [grpCurrencies, grpAccountingPeriods, grpMiscellaneousFlags, grpDataRetention]
        grpCurrencies: {Label=Currencies, Stretch=horizontally}
            Controls: [cmbBaseCurrency, cmbIntlCurrency]
        grpAccountingPeriods: {Label=Accounting Periods, Stretch=horizontally}
            Controls: [rgrCalendarModeRadio, nudNumberOfAccountingPeriods, dtpFinancialYearStartDate, nudCurrentPeriod, btnViewCalendar]
        grpMiscellaneousFlags: {Label=Miscellaneous, Stretch=horizontally}
            Controls: [pnlSuspenseAccounts, pnlBudget, pnlFwdPosting, pnlBranchProcess]
        grpDataRetention: {Label=Data Retention, Stretch=horizontally}
            Controls: [nudActualsDataRetention, nudGiftDataRetention]
        pnlSuspenseAccounts:
            Controls: [chkSuspenseAccountFlag]
        pnlBudget:
            Controls: [chkBudgetControlFlag]
        pnlFwdPosting:
            ControlsOrientation: horizontal
            Controls: [chkUseDefaultFwdPostingPeriods, nudNumberFwdPostingPeriods]
        pnlBranchProcess:
            Controls: [chkBranchProcessing]
            
        rgrCalendarModeRadio:
            Controls: [rbtMonthly, rbtNonMonthly]
            NoLabel: true
            BorderVisible: false
            ControlsOrientation: horizontal
        rbtMonthly:
            Label: Monthly
            OnChange: CalendarModeChanged
            ParameterValue: Monthly
        rbtNonMonthly:
            Label: Non-monthly
            OnChange: CalendarModeChanged
            ParameterValue: Non-monthly
        
        cmbBaseCurrency: {List=CurrencyCodeList}
        cmbIntlCurrency: {List=CurrencyCodeList}
        nudNumberOfAccountingPeriods: {Label=Number of Periods, Validation=true}
        nudCurrentPeriod: {Label=Current Period, Validation=true}
        btnViewCalendar: {Label=View Calendar, ActionClick=OnBtnCalendar}
        dtpFinancialYearStartDate: {Label=First Day of the Financial Year, Align=bottom}
        chkSuspenseAccountFlag: {Label=Allow use of suspense accounts?, CheckBoxAttachedLabel=right, Validation=true}
        chkBudgetControlFlag: {Label=Budget control, CheckBoxAttachedLabel=right}
        chkUseDefaultFwdPostingPeriods: {Label=Use default forward posting periods, CheckBoxAttachedLabel=right, OnChange=UseDefaultFwdPostingPeriodsChanged}
        nudNumberFwdPostingPeriods: {Label=Forward Posting Periods, Validation=true}
        chkBranchProcessing: {Label=Branch processing, CheckBoxAttachedLabel=right}
        nudActualsDataRetention: {Label=Actuals Data Retention Period}
        #nudBudgetDataRetention: {Label=Budget Data Retention Period}
        nudGiftDataRetention: {Label=Gift Data Retention Period}
