RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MFinance.Gui.Setup
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    DetailTable: AFreeformAnalysis
    UsingNamespaces: [Ict.Petra.Shared.MFinance.Account.Data,Ict.Petra.Shared.MFinance.Account.Validation]
    FormType: edit
    Template: controlMaintainTable
    Actions:
        actNew: {Label=&New, ActionClick=NewRow}
        actDelete: {Label=&Delete, ActionClick=DeleteRecord}      
    Controls:
        pnlContent:
            Controls: [pnlGrid, pnlDetails]
            Dock: Fill
        pnlGrid:
            Dock: Fill
            Controls: [pnlDetailTop,grdDetails, pnlButtons]
        pnlButtons:
            Dock: Right
            Controls: [btnNew, btnDelete]
        btnNew:
            Action: actNew
        btnDelete:
            Action: actDelete
        grdDetails:
            Dock: Fill
            Columns: [AFreeformAnalysis.AnalysisValue, AFreeformAnalysis.Active]
            ActionFocusRow: FocusedRowChanged
        pnlDetails:
            Height: 150
            Dock: Bottom
            Controls:
                Row0: [txtDetailAnalysisValue]
                Row1: [chkDetailActive]
        txtDetailAnalysisValue: {Label=Value, Width=400}
        chkDetailActive: {Label=Active}
        pnlDetailTop:
            Dock: Top
            Controls: [txtHeaderLedgerNumber]
        txtHeaderLedgerNumber: {Label=Values for this Type and Ledger Number,ReadOnly=true}
    Menu:
        mniAnalysisValues:
    Toolbar:
        tbbNew:
            Label: New Analysis Value