RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MFinance.Gui.Setup
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    DetailTable: AFreeformAnalysis
    UsingNamespaces: [Ict.Petra.Shared.MFinance.Account.Data,Ict.Petra.Shared.MFinance.Account.Validation]
    FormType: edit
    Template: controlMaintainTable
    Actions:
        actNew: {Label=&New, ActionClick=NewRow}
        actDelete: {Label=&Delete, ActionClick=DeleteRecord}      
    Controls:
        pnlContent:
            Controls: [pnlDetailTop, pnlGrid, pnlDetails]
            Dock: Fill
        pnlGrid:
            Dock: Fill
            Controls: [pnlFilterAndFind, pnlButtons, grdDetails]
        pnlFilterAndFind:
            ExpandedWidth: 175
            FilterControls: [txtDetailAnalysisValue, chkDetailActive]
            FindControls: [txtDetailAnalysisValue]
        pnlButtons:
            Dock: Bottom
            Controls: [btnNew, btnDelete]
            ControlsOrientation: horizontal
        btnNew:
            Action: actNew
            Width: 80
        btnDelete:
            Action: actDelete
            Width: 80
        grdDetails:
            Dock: Fill
            Columns: [AFreeformAnalysis.AnalysisValue, AFreeformAnalysis.Active]
            SortOrder: AFreeformAnalysis.AnalysisValue ASC
            ActionFocusRow: FocusedRowChanged
        pnlDetails:
            Height: 70
            Dock: Bottom
            Controls:
                Row0: [txtDetailAnalysisValue]
                Row1: [chkDetailActive]
        txtDetailAnalysisValue: {Label=Value, Width=400}
        chkDetailActive: {Label=Active}
        pnlDetailTop:
            Dock: Top
            Controls: [txtHeaderLedgerNumber]
        txtHeaderLedgerNumber: {Label=Values for this Type and Ledger Number,ReadOnly=true}
    Menu:
        mniAnalysisValues:
